import { useEffect, useMemo, useState } from 'react'
import { Search, MapPin, Heart, Sun, Moon, Monitor, Navigation, Wind, Droplets, Gauge, Eye, Sunrise, Sunset, Umbrella, RefreshCw, X, ChevronRight } from 'lucide-react'
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts'
import { conditionMeta, countryName, geocode, getWeather, reverseGeocode, readCached } from './services/weather'
import './styles.css'

const initialPlace = { name: 'Manila', state: 'Metro Manila', country: 'PH', lat: 14.5995, lon: 120.9842 }
const unitSymbol = u => u === 'metric' ? '°' : '°'
const formatTemp = (n, units, decimals = 0) => `${Math.round(n ?? 0)}${unitSymbol(units)}`
const time = (dt, tz = 0, opts = {}) => new Intl.DateTimeFormat([], { hour: 'numeric', minute: opts.minute ? '2-digit' : undefined, timeZone: 'UTC' }).format(new Date((dt + tz) * 1000))
const day = dt => new Intl.DateTimeFormat([], { weekday: 'short' }).format(new Date(dt * 1000))

function Button({ children, className = '', ...props }) { return <button className={`icon-button ${className}`} {...props}>{children}</button> }
function Header({ query, setQuery, onSearch, units, setUnits, theme, setTheme, onLocate }) { return <header className="topbar"><div className="brand"><div className="brand-mark"><Sun size={18}/></div><span>weatherly</span></div><form className="search" onSubmit={e => { e.preventDefault(); onSearch(query) }}><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search city or country" aria-label="Search city"/><Button type="button" onClick={() => setQuery('')} aria-label="Clear search"><X size={15}/></Button></form><div className="header-actions"><button className="location-btn" onClick={onLocate}><Navigation size={16}/> <span>Use my location</span></button><div className="segmented" aria-label="Temperature unit"><button className={units === 'metric' ? 'active' : ''} onClick={() => setUnits('metric')}>°C</button><button className={units === 'imperial' ? 'active' : ''} onClick={() => setUnits('imperial')}>°F</button></div><div className="theme-toggle" aria-label="Theme"><button className={theme === 'light' ? 'active' : ''} onClick={() => setTheme('light')}><Sun size={16}/></button><button className={theme === 'dark' ? 'active' : ''} onClick={() => setTheme('dark')}><Moon size={16}/></button><button className={theme === 'system' ? 'active' : ''} onClick={() => setTheme('system')}><Monitor size={16}/></button></div></div></header> }
function Section({ title, eyebrow, children, action }) { return <section className="section"><div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action}</div>{children}</section> }
function Hero({ data, units, favorite, onFavorite }) { const meta = conditionMeta(data.current.weather?.[0]?.id, data.current.weather?.[0]?.icon); const loc = data.location; return <section className={`hero weather-${meta.category}`} style={{ '--weather-image': `url(${meta.image})` }}><div className="hero-top"><div><div className="eyebrow light">CURRENT CONDITIONS</div><h1>{loc.name}<span>, {countryName(loc.country)}</span></h1><p className="muted-light">{loc.state || 'Today'} · {new Intl.DateTimeFormat([], { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())}</p></div><Button className="favorite" onClick={onFavorite} aria-label="Favorite location"><Heart size={20} fill={favorite ? 'currentColor' : 'none'}/></Button></div><div className="hero-main"><div className="weather-symbol" aria-label={meta.label}>{meta.symbol}</div><div><div className="temperature">{formatTemp(data.current.temp, units)}</div><div className="condition">{meta.label}</div><div className="feels">Feels like {formatTemp(data.current.feels_like, units)} <span>·</span> H {formatTemp(data.daily?.[0]?.temp?.max || data.current.temp + 3, units)} &nbsp; L {formatTemp(data.daily?.[0]?.temp?.min || data.current.temp - 4, units)}</div></div></div><div className="hero-footer"><span><Wind size={15}/> {Math.round(data.current.wind_speed)} {units === 'metric' ? 'km/h' : 'mph'}</span><span><Droplets size={15}/> {data.current.humidity}% humidity</span><span><Umbrella size={15}/> {Math.round((data.hourly?.[0]?.pop || 0) * 100)}% rain chance</span></div></section> }
function Hourly({ data, units }) { const tz = data.location.timezone || 0; const chart = data.hourly.map(x => ({ time: time(x.dt, tz), temp: Math.round(x.temp), rain: Math.round((x.pop || 0) * 100) })); return <Section title="Next hours" eyebrow="HOURLY FORECAST"><div className="hourly-row">{data.hourly.slice(0, 8).map((x, i) => <div className={`hour ${i === 0 ? 'now' : ''}`} key={x.dt}><span>{i === 0 ? 'Now' : time(x.dt, tz)}</span><b>{conditionMeta(x.weather?.[0]?.id, x.weather?.[0]?.icon).symbol}</b><strong>{formatTemp(x.temp, units)}</strong><small>{Math.round((x.pop || 0) * 100)}% rain</small></div>)}</div><div className="chart-card"><div className="chart-label"><span>Temperature</span><span className="chart-legend"><i className="dot temp-dot"/> forecast <i className="dot rain-dot"/> rain chance</span></div><ResponsiveContainer width="100%" height={190}><AreaChart data={chart} margin={{ top: 20, right: 8, left: -28, bottom: 0 }}><defs><linearGradient id="tempFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f4b860" stopOpacity={.3}/><stop offset="100%" stopColor="#f4b860" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }}/><YAxis hide domain={['dataMin - 2', 'dataMax + 2']}/><Tooltip contentStyle={{ background: 'var(--card)', border: '1px solid var(--line)', borderRadius: 12 }} formatter={(v, name) => [name === 'temp' ? `${v}°` : `${v}%`, name === 'temp' ? 'Temp' : 'Rain']}/><Area type="monotone" dataKey="temp" stroke="#e69542" strokeWidth={3} fill="url(#tempFill)"/><Area type="monotone" dataKey="rain" stroke="#76a9c9" strokeWidth={2} fill="none" strokeDasharray="5 5"/></AreaChart></ResponsiveContainer></div></Section> }
function Daily({ data, units }) { return <Section title="The week ahead" eyebrow="8-DAY FORECAST"><div className="daily-list">{data.daily.map((x, i) => { const meta = conditionMeta(x.weather?.[0]?.id, x.weather?.[0]?.icon); return <div className="daily" key={x.dt}><strong>{i === 0 ? 'Today' : day(x.dt)}</strong><span className="daily-weather">{meta.symbol} <span>{meta.label}</span></span><span className="daily-rain">{Math.round((x.pop || 0) * 100)}%</span><b>{formatTemp(x.temp.max, units)} <small>{formatTemp(x.temp.min, units)}</small></b><ChevronRight size={17}/></div> })}</div></Section> }
function Metric({ icon: Icon, label, value, detail }) { return <div className="metric"><div className="metric-icon"><Icon size={17}/></div><div><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div></div> }
function Details({ data, units }) { const c = data.current; const aqi = data.air?.main?.aqi; return <Section title="Conditions & details" eyebrow="AT A GLANCE"><div className="metrics"><Metric icon={Droplets} label="Humidity" value={`${c.humidity}%`} detail="Comfortable"/><Metric icon={Gauge} label="Pressure" value={`${c.pressure} hPa`} detail="Steady"/><Metric icon={Eye} label="Visibility" value={`${(c.visibility / 1000).toFixed(1)} km`} detail="Clear view"/><Metric icon={Wind} label="Wind" value={`${Math.round(c.wind_speed)} ${units === 'metric' ? 'km/h' : 'mph'}`} detail={`${Math.round(c.wind_deg)}° · gusts ${Math.round(c.wind_gust || c.wind_speed * 1.3)}`}/><Metric icon={Sun} label="UV index" value={c.uvi ?? '—'} detail={c.uvi > 5 ? 'High — take care' : 'Low'}/><Metric icon={Droplets} label="Dew point" value={formatTemp(c.dew_point || c.temp - 6, units)} detail="Comfortable"/></div>{aqi && <div className="air-quality"><div><span className="eyebrow">AIR QUALITY</span><h3>{['','Good','Fair','Moderate','Poor','Very poor'][aqi]}</h3><p>AQI {aqi} · PM2.5 {data.air.components.pm2_5.toFixed(1)} μg/m³</p></div><div className="aqi-bar"><i style={{ left: `${aqi * 18}%` }}/></div></div>}</Section> }
function SunCard({ data }) { const c = data.current; return <div className="sun-card"><div className="sun-heading"><div><span className="eyebrow">DAYLIGHT</span><h3>Sunrise & sunset</h3></div><Sunrise size={23}/></div><div className="sun-times"><span><small>Sunrise</small><b>{time(c.sunrise, data.location.timezone, { minute: true })}</b></span><div className="sun-arc"><i/></div><span><small>Sunset</small><b>{time(c.sunset, data.location.timezone, { minute: true })}</b></span></div></div> }
function Favorites({ favorites, onSelect, onRemove }) { if (!favorites.length) return null; return <Section title="Your places" eyebrow="SAVED LOCATIONS"><div className="favorites">{favorites.map(f => <div className="favorite-item" key={f.lat + f.lon}><button onClick={() => onSelect(f)}><MapPin size={16}/><span>{f.name}<small>{f.country}</small></span></button><Button onClick={() => onRemove(f)} aria-label={`Remove ${f.name}`}><X size={15}/></Button></div>)}</div></Section> }
function App() { const [place, setPlace] = useState(initialPlace), [data, setData] = useState(null), [query, setQuery] = useState(''), [suggestions, setSuggestions] = useState([]), [units, setUnits] = useState(localStorage.getItem('units') || 'metric'), [theme, setTheme] = useState(localStorage.getItem('theme') || 'system'), [loading, setLoading] = useState(true), [error, setError] = useState(''), [favorites, setFavorites] = useState(JSON.parse(localStorage.getItem('favorites') || '[]')), [recent, setRecent] = useState(JSON.parse(localStorage.getItem('recent') || '[]'))
  useEffect(() => { const root = document.documentElement; root.classList.toggle('dark', theme === 'dark' || (theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches)); localStorage.setItem('theme', theme) }, [theme])
  useEffect(() => { localStorage.setItem('units', units); load(place, units) }, [units])
  useEffect(() => { load(place, units) }, [])
  async function load(p, u) { setLoading(true); setError(''); try { const result = await getWeather(p, u); setData(result); localStorage.setItem('lastPlace', JSON.stringify(p)) } catch { const cached = readCached(p, u); if (cached) { setData(cached); setError('You’re offline — showing the last available weather data.') } else setError('Weather data is temporarily unavailable. Please try again.') } finally { setLoading(false) } }
  async function search(value) { if (!value.trim()) { setError('Enter a city or country to search.'); return }; try { const list = await geocode(value); setSuggestions(list); if (list.length === 1) selectPlace(list[0]); else if (!list.length) setError('We couldn’t find that location.') } catch { setError('Search is temporarily unavailable.') } }
  function selectPlace(p) { setPlace(p); setQuery(''); setSuggestions([]); setRecent(prev => { const next = [p, ...prev.filter(x => x.name !== p.name)].slice(0, 5); localStorage.setItem('recent', JSON.stringify(next)); return next }); load(p, units) }
  function toggleFavorite() { setFavorites(prev => { const exists = prev.some(x => x.name === place.name); const next = exists ? prev.filter(x => x.name !== place.name) : [...prev, place].slice(-6); localStorage.setItem('favorites', JSON.stringify(next)); return next }) }
  function locate() { if (!navigator.geolocation) return setError('Location is not available in this browser.'); navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { selectPlace(await reverseGeocode(coords.latitude, coords.longitude)) } catch { setError('We couldn’t determine your location.') } }, () => setError('Location permission was denied.')) }
  const isFavorite = favorites.some(x => x.name === place.name); const maxRain = data ? Math.max(...data.hourly.slice(0, 8).map(x => x.pop || 0)) : 0
  return <><Header {...{ query, setQuery, onSearch: search, units, setUnits, theme, setTheme, onLocate: locate }}/>{suggestions.length > 1 && <div className="suggestions">{suggestions.map(s => <button key={`${s.lat}-${s.lon}`} onClick={() => selectPlace(s)}><MapPin size={16}/><span>{s.name}<small>{[s.state, s.country].filter(Boolean).join(', ')}</small></span></button>)}</div>}<main>{error && <div className="notice"><span>{error}</span><Button onClick={() => load(place, units)} aria-label="Retry"><RefreshCw size={16}/></Button></div>}{loading ? <div className="loading-grid"><div className="skeleton hero-skeleton"/><div className="skeleton"/><div className="skeleton"/></div> : data && <><Hero data={data} units={units} favorite={isFavorite} onFavorite={toggleFavorite}/><div className="content-grid"><div><Hourly data={data} units={units}/><Daily data={data} units={units}/></div><aside><div className="rain-card"><div><span className="eyebrow">PRECIPITATION</span><h3>{maxRain > .25 ? 'Rain is possible' : 'Mostly dry ahead'}</h3><p>{Math.round(maxRain * 100)}% highest chance in the next few hours.</p></div><div className="rain-drop">{maxRain > .25 ? '☔' : '◌'}</div></div><Details data={data} units={units}/><SunCard data={data}/></aside></div><Favorites favorites={favorites} onSelect={selectPlace} onRemove={f => setFavorites(prev => { const n = prev.filter(x => x.name !== f.name); localStorage.setItem('favorites', JSON.stringify(n)); return n })}/>{recent.length > 0 && <div className="recent">Recent searches: {recent.map((r, i) => <button key={r.name + i} onClick={() => selectPlace(r)}>{r.name}</button>)}</div>}</>}</main><footer>Weatherly <span>·</span> Forecast data by OpenWeather <span>·</span> Updated just now</footer></> }
export default App
